### ISSUE TITLE
Getting Error During Installation

### ISSUE THREAD

**Issue by GaneshKandu** [albandes/helpdezk#1]
Hi Tring to install helpdezk **Version 1.1.0** but Getting Error 

Table **'tmp_blobs'** doesn't exist

 **Step 7 out of 7 - Install**
line: 69 -- Invalid query. Err 1146 - Table 'soft_helpdezk11.tmp_blobs' doesn't exist
**query**: SELECT \* from tmp_blobs ;

**Comment by GaneshKandu** [comment]
Sorry ! Installation Done "includes\config\config.php" was not writable

**Comment by GaneshKandu** [comment]
Hi

I think This May be solution 

```php
	   // Load and explode the sql file
	   $f = fopen($sqlFileToExecute,"r+");
	   $sqlFile = fread($f,filesize($sqlFileToExecute));
	   $sqlArray = explode(';',$sqlFile);
```
installer/banco.sql need to be writable

**Comment by albandes** [comment]
Hi.

Are you try install Helpdezk in Linux ?

**Comment by GaneshKandu** [comment]
yes ! on Non-SuPHP server

**Comment by albandes** [comment]
OK.

I will try to install on a Linux machine.
I will return the result today.
