### ISSUE TITLE
Add on SourceForge that the project has moved to GitHub

### ISSUE THREAD

**Issue by Neustradamus** [albandes/helpdezk#124]
Can you add that the project has moved to GitHub?
- https://sourceforge.net/projects/helpdezk/

Can you disable unused sections too?

**Comment by albandes** [comment]
@Neustradamus 

I did the integration between Sourceforge and Github.
With each new release, Sourceforge is updated.
But, do you think it is better to check the option that helpdezk has been moved to github?

**Comment by Neustradamus** [comment]
Better to add that the project has moved on GitHub.
But I think that you can upload new builds after it on SF.

**Comment by Neustradamus** [comment]
@albandes: Why have you closed it without solution?

Example:
- https://sourceforge.net/projects/ultravnc/

**Comment by Neustradamus** [comment]
@albandes: Any news?

**Comment by albandes** [comment]
@Neustradamus 

Sourceforge updates the downloadable files with each new release generated on github. I already made this configuration.

Do you find it interesting to keep both?

**Comment by Neustradamus** [comment]
@albandes: It is possible to add the "moved box" on the Sourceforge project page?

It does not change the /files/ from SF.

**Comment by Neustradamus** [comment]
@albandes: It is possible to have an answer and a solution?
