### ISSUE TITLE
httpS is missing for main website and demo website

### ISSUE THREAD

**Issue by Neustradamus** [albandes/helpdezk#125]
Can you add httpS support, drop "www" and redirect to https://helpdezk.org/*?
- http://www.helpdezk.org/*
- https://www.helpdezk.org/*
- http://helpdezk.org/*

http://demo.helpdezk.org/* to https://demo.helpdezk.org/*

Informations (better for SEO, etc.):
- https://dropwww.com/why

**Comment by albandes** [comment]
Hello @Neustradamus .

The site is already OK without the www. I kept the www for now, due to indexing on google.

I am preparing the server for TSL, so httpS will be OK soon.

Thank you for your collaboration.

Regards

**Comment by Neustradamus** [comment]
@albandes: Please add rules of redirections.

And when you have added httpS, please update the rules.

Google will be updated directly and no lost.

Example with the downloads page will be redirected to https://helpdezk.org/downloads from:
- http://helpdezk.org/downloads
- http://www.helpdezk.org/downloads
- https://www.helpdezk.org/downloads

**Comment by albandes** [comment]
Hello

@Neustradamus ,

I think everything is OK with httpS, please check.

Regards

**Comment by Neustradamus** [comment]
@albandes: Perfect, thanks a lot!
