### ISSUE TITLE
Why is the page after I installed it blank?

### ISSUE THREAD

**Issue by Balis0ng** [albandes/helpdezk#3]
After my debugging, I found that the 16th line in /app/modules/admin/controllers/loginController.php has a function not found.

**$this->pipeInclude('ldapClass.php');**`

Can help me solve this problem?

**Comment by albandes** [comment]
Please wait until the 16th, Tuesday. I will be uploading a new release where this bug will be fixed.

**Comment by DeXon18** [comment]
I just installed the latest version and it seems that the problem persists

The controller does not exist: app/modules/community/controllers/adminController.php

Can you solve this problem?

**Comment by albandes** [comment]
Hello.

Please wait until tomorrow January 10. We will be releasing a new version
where this issue will be resolved.

Regards

*Rogério Albandes*

*Owner at Pipegrep*
*Helpdezk - Project Leader*
*IT Coordinator at Instituto Educacional MQ*
*Master of Science in **Electronic Engineering and Computing - UCPel*


Em qui., 9 de jan. de 2020 às 09:55, DeXon <notifications@github.com>
escreveu:

**Comment by DeXon18** [comment]
Perfect friend is waiting.

**Comment by DeXon18** [comment]
I've checked that it doesn't generate the config.php file so it's still losing configurations,

**Comment by albandes** [comment]
Hello

The new version is now available, sorry for the delay.

Bests Regards

*Rogério Albandes*

*Owner at Pipegrep*
*Helpdezk - Project Leader*
*IT Coordinator at Instituto Educacional MQ*
*Master of Science in **Electronic Engineering and Computing - UCPel*


Em qui., 9 de jan. de 2020 às 10:10, DeXon <notifications@github.com>
escreveu:
