### ISSUE TITLE
Table 'helpdezk.hdk_tbnote' doesn't exist

### ISSUE THREAD

**Issue by GaneshKandu** [albandes/helpdezk#60]
Hi,

Getting this error while install of ``helpdezk 1.1.2`` on php 5.5

```
mysql error: Table 'helpdezk.hdk_tbnote' doesn't exist
CREATE OR REPLACE VIEW hdk_viewnotesdata AS (select `n`.`idnote` AS `idnote`,`n`.`code_request` AS `code_request`,`n`.`idperson` AS `idperson`,`p`.`name` AS `name`,`n`.`entry_date` AS `entry_date`,`n`.`execution_date` AS `execution_date`,`n`.`start_hour` AS `start_hour`,`n`.`finish_hour` AS `finish_hour`,`n`.`minutes` AS `minutes`,`n`.`idtype` AS `idtype`,`n`.`IND_CHAMADO` AS `IND_CHAMADO`,`n`.`ip_adress` AS `ip_adress`,`n`.`public` AS `public`,`n`.`hour_type` AS `hour_type`,`n`.`service_value` AS `service_value`,`n`.`callback` AS `callback`,`n`.`description` AS `description` from (`hdk_tbnote` `n` join `tbperson` `p`) where `p`.`idperson` = `n`.`idperson`); 
```

database i created is still blank

**Comment by albandes** [comment]
Hello.

*hdk_viewnotesdata* is a VIEW, used to view the notes of tickets.

The probable cause of this error is that your mysql user does not have
privileges to create VIEWS.
As this error occurred, the bank installation process was aborted.

You can try:

1. Check the privileges of your mysql user;
2. If you are familiar with mysql you can directly import the data in:

installer/dumps/db-install-routines.sql

installer/dumps/db-install-tables.sql

installer/dumps/db-install-views.sql

Regards

*Rogério Albandes*

*Owner at Pipegrep*
*Helpdezk - Project Leader*
*IT Coordinator at Instituto Educacional MQ*
*Master of Science in **Electronic Engineering and Computing - UCPel*


Em ter., 21 de jan. de 2020 às 07:57, Ganesh Kandu <notifications@github.com>
escreveu:

**Comment by GaneshKandu** [comment]
> The probable cause of this error is that your mysql user does not have privileges to create VIEWS.

I am used ``root`` user for install

**Comment by albandes** [comment]
Please, try to import this dump files:

installer/dumps/db-install-routines.sql
installer/dumps/db-install-tables.sql
installer/dumps/db-install-views.sql



*Rogério Albandes*

*Owner at Pipegrep*
*Helpdezk - Project Leader*
*IT Coordinator at Instituto Educacional MQ*
*Master of Science in **Electronic Engineering and Computing - UCPel*


Em ter., 21 de jan. de 2020 às 09:18, Ganesh Kandu <notifications@github.com>
escreveu:

**Comment by helpdezk-develop** [comment]
Hello.

Sorry, there is an error in the installation program.

Please uncomment lines 38 and 39 of installer/ajax/step_7_proced.php.
I will fix the bug and release a new release soon.

Regards

**Comment by albandes** [comment]
Hello.

Last release, fix the issue: https://github.com/albandes/helpdezk/releases/tag/v1.1.3
