### ISSUE TITLE
The used table type doesn't support FULLTEXT indexes

### ISSUE THREAD

**Issue by GaneshKandu** [albandes/helpdezk#62]
- 1

Getting error while install helpdezk 1.1.3

```
mysql error: The used table type doesn't support FULLTEXT indexes

CREATE TABLE `tbmodule` ( `idmodule` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(20) NOT NULL, `index` int(11) DEFAULT NULL, `status` char(1) NOT NULL DEFAULT 'A', `path` varchar(20) DEFAULT NULL, `smarty` varchar(50) DEFAULT NULL, `class` varchar(50) DEFAULT NULL, `headerlogo` varchar(255) DEFAULT NULL, `reportslogo` varchar(255) DEFAULT NULL, `tableprefix` char(3) DEFAULT NULL, `defaultmodule` char(4) DEFAULT NULL, PRIMARY KEY (`idmodule`), FULLTEXT KEY `defaultmodule` (`defaultmodule`) ) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
 ```

----------------------------------------------------------------------------------------------

- 2

what minimum php-version required to install ``helpdezk`` ?

---------------------------------------------------------------------------------------------

- 3

``helpdezk version is not changed in ``version.txt`` 
 
its still ```helpdezk-community-1.1.1 ```  in ``helpdezk-1.1.3``

**Comment by albandes** [comment]
Hello

1. Change Mysql to version 5.6 or higher, I use 10.4.10-MariaDB ;
2. PHP 7 . I use 7.3.12;
3. Tks, I change in the next version !

Regards
