### ISSUE TITLE
Helpdezk 1.1.4. Missing Jquery file error

### ISSUE THREAD

**Issue by prbt2016** [albandes/helpdezk#67]
Hello,

I manually installed Helpdezk on PHP 7.0 , MYSQL 5.6, Apache 2.2.34. However after successful manual installation when i visit the url i get the following error  i.e : 

There is no Jquery file in: /{{PATH}}/{{TO}}/{{HELPDEZK}}/includes/js/ : 

Also I  checked the folder /includes/js/, the file 'jquery-2.1.1.js' is present.

What could be causing the issue?. Could you please check this at your end ?.

**Comment by albandes** [comment]
Hello

Didn't you use the installation program (http: //.../installer)?
The installation program creates the config.php file located in the includes / config folder

In this file the version of jquery is defined:

$ config ['jquery'] = 'jquery-2.1.1.js';

It is recommended that you use the installation program, if you don't want to, I can send you an example of config.php

Regards

**Comment by prbt2016** [comment]
![test](https://user-images.githubusercontent.com/17871448/74148872-772e0c80-4c2c-11ea-9f98-efcf508c7403.png)

This is the screenshot of the installer created config.php file's $config['jquery'] variable.

>>Didn't you use the installation program (http: //.../installer)?

Yes I used the script's installer program yet  I get the above error i.e:

There is no Jquery file in: /{{PATH}}/{{TO}}/{{HELPDEZK}}/includes/js/ .

**Comment by helpdezk-develop** [comment]
OK.

I will try to reproduce this error.
One question, what OS are you using? Windows, Linux?

Regards

**Comment by prbt2016** [comment]
I am using Linux( Centos 6.4 Final).

**Comment by albandes** [comment]
Hello

There is an error in the config.php's  creation script, it left a blank space at the end:

```
$ config ["jquery"] = "jquery-2.1.1.js ";
```
Just remove the space that will work:
```
$ config ["jquery"] = "jquery-2.1.1.js";
```
In Linux, php's file_exists() function considers blanks.

In the next release this problem will definitely be solved.

Thank you for your observation

**Comment by prbt2016** [comment]
Hello @albandes,

Indeed there was a blank space and after removing it ,script works absolutely fine. Thanks for the fix.

Regards.
